apiVersion: v1
kind: Service
metadata:
  name: {{ include "crauti.fullname" . }}
  labels:
    {{- include "crauti.labels" . | nindent 4 }}
  {{- if .Values.exposeAdminUI }}
  annotations:
    ferama.github.io/crauti: |
      enabled: true
      upstreamHttpPort: 8181
      mountPoints:
        - source: /
          path: /
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
    - port: 443
      targetPort: 443
      protocol: TCP
      name: https
    - port: 8181
      targetPort: admin
      protocol: TCP
      name: admin
  externalTrafficPolicy: Local
  selector:
    {{- include "crauti.selectorLabels" . | nindent 4 }}
