{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "crauti.serviceAccountName" . }}
  labels:
    {{- include "crauti.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "crauti.fullname" . }}-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "crauti.labels" . | nindent 4 }}
rules:
- apiGroups:
    - ''
  resources:
    - 'services'
  verbs: 
    - 'get'
    - 'watch'
    - 'list'
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "crauti.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "crauti.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "crauti.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "crauti.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
