apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8svpn.fullname" . }}
  labels:
    {{- include "k8svpn.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "k8svpn.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "k8svpn.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "k8svpn.fullname" . }}-service-account
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          env:
            - name: SERVICE_NAME
              value: {{ include "k8svpn.fullname" . }}
            - name: INTERNAL_SUBNET
              value: {{ .Values.internalSubnet }}
            - name: ALLOWEDIPS
              value: {{ .Values.allowedips }}
            - name: SERVERURL
              value: {{ .Values.serverUrl }}
            - name: SERVERPORT
              value: {{ .Values.service.port | quote }}
          securityContext:
            privileged: true
          readinessProbe:
            exec:
              command:
              - cat
              - /config/peer1/peer1.conf
            initialDelaySeconds: 5
            periodSeconds: 5
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
