apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kali.fullname" . }}-auth
data:
{{ if .Values.authorizedKeys }}
  authorized_keys: {{- .Values.authorizedKeys | b64enc | indent 1}}
{{ else }}
  authorized_keys: ""
{{ end }}
