{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kali.serviceAccountName" . }}
  labels:
    {{- include "kali.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "kali.fullname" . }}-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kali.labels" . | nindent 4 }}
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs: 
  - '*'
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "kali.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kali.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "kali.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "kali.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
