apiVersion: v1
kind: Service
metadata:
  name: {{ include "kali.fullname" . }}
  labels:
    {{- include "kali.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{ if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{ end }}
  ports:
    {{- if .Values.mapPortRange }}
      {{- $iter := untilStep (int .Values.mapPortRange.start) (int .Values.mapPortRange.end) 1 -}}
      {{- range $index, $port := $iter }}
    - name: port-{{ $index }}
      port: {{ $port }}
      targetPort: {{ $port }}
      protocol: TCP
      {{- end }}
    {{- end }}
    - name: ssh
      port: 2222
      targetPort: ssh
      protocol: TCP
      {{ if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{ end }}
  selector:
    {{- include "kali.selectorLabels" . | nindent 4 }}