kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "vipien.fullname" . }}-role
  labels:
    {{- include "vipien.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ''
  resources:
  - 'services'
  - 'namespaces'
  verbs: 
  - 'get'
  - 'list'
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "vipien.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "vipien.fullname" . }}-service-account
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "vipien.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io