apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vipien.fullname" . }}
  labels:
    {{- include "vipien.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "vipien.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "vipien.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "vipien.fullname" . }}-service-account
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          env:
            - name: SERVICE_NAME
              value: {{ include "vipien.fullname" . }}
            - name: INTERNAL_SUBNET
              value: {{ .Values.internalSubnet }}
            - name: ALLOWED_IPS
              value: {{ .Values.allowedips }}
            - name: SERVER_PUBLIC_URL
              value: {{ .Values.serverUrl }}
            - name: SERVER_PUBLIC_PORT
              value: {{ .Values.service.port | quote }}
            - name: ENABLE_UI
              value: {{ .Values.enableUI | quote }}
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_MODULE
            privileged: true
          readinessProbe:
            exec:
              command:
              - cat
              - /config/peers/1.conf
            initialDelaySeconds: 5
            periodSeconds: 5
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          {{- if .Values.dataVolume.enabled }}
            - name: {{ include "vipien.fullname" . }}-pvc
              mountPath: /config
          {{- end }}  
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      {{- if .Values.dataVolume.enabled }}
        - name: {{ include "vipien.fullname" . }}-pvc
          persistentVolumeClaim:
            claimName: {{ include "vipien.fullname" . }}-pvc
      {{- end }}
