apiVersion: v1
kind: Service
metadata:
  name: {{ include "vipien.fullname" . }}-wg
  labels:
    {{- include "vipien.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    # wireguard
    - protocol: UDP
      name: wireguard
      {{ if ( eq .Values.service.type "NodePort" ) }}
      nodePort: {{ .Values.service.port }}
      {{ end }}
      port: {{ .Values.service.port }}
      targetPort: 51820
    {{ if .Values.enableUI }}
    - protocol: TCP
      name: ui
      port: 8080
      targetPort: 8080
    {{ end }}
  selector:
    {{- include "vipien.selectorLabels" . | nindent 4 }}
