apiVersion: v1
kind: Service
metadata:
  name: {{ include "rospo.fullname" . }}
  labels:
    {{- include "rospo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 2222
      targetPort: ssh
      protocol: TCP
      name: ssh
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "rospo.selectorLabels" . | nindent 4 }}
