apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "rospo.fullname" . }}
  labels:
    {{- include "rospo.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "rospo.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "rospo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "rospo.selectorLabels" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: 10
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "rospo.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          {{- if and .Values.chroot.enabled ( not .Values.securityContext ) }}
          securityContext:
            privileged: true
            capabilities:
              add: ["CAP_SYS_CHROOT"]
          {{- else }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.chroot.enabled }}
          command: ["/bin/sh"]
          args:
            - -c
            - |
              set -e
              if [ ! -f /data/chroot-ready ]; then
                apt update
                apt install -y schroot debootstrap
                debootstrap jammy /data http://archive.ubuntu.com/ubuntu/
 
                cp /usr/local/bin/rospo /data/usr/local/bin/rospo
                mkdir /data/etc/rospo

                chroot /data sed -i 's/^#force_color_prompt=yes/force_color_prompt=yes/' /etc/skel/.bashrc
                chroot /data adduser --gecos "" --disabled-password rospo
                echo "rospo ALL=(ALL) NOPASSWD: ALL" >> /data/etc/sudoers
                chroot /data addgroup rospo sudo
              fi

              cp -r /etc/rospo/* /data/etc/rospo
              cp /etc/hosts /data/etc/hosts

              mount proc /data/proc -t proc
              mount sysfs /data/sys -t sysfs
              mount -o bind /dev /data/dev/
              mount -t devpts pts /data/dev/pts/
              mount -o bind /dev/shm /data/dev/shm

              {{- if .Values.serviceAccount.create }}
              mkdir -p /data/run/secrets/kubernetes.io/serviceaccount
              mount -o bind /run/secrets/kubernetes.io/serviceaccount /data/run/secrets/kubernetes.io/serviceaccount
              {{- end }}

              {{- range .Values.extraVolumeMounts }}
                mkdir -p /data/{{ .mountPath }}
                mount -o bind {{ .mountPath }} /data/{{ .mountPath }}
              {{- end }}

              touch /data/chroot-ready

              # rospo /etc/rospo/rospo.yaml

              chroot /data /bin/bash <<"EOT"
                chmod 666 /dev/ptmx
                {{ if .Values.customUserId }}
                usermod -u {{ .Values.customUserId }} rospo
                {{ else }}
                usermod -u 1000 rospo
                {{ end }}
                runuser -l rospo -c 'rospo /etc/rospo/rospo.yaml'
              EOT

          {{- else if .Values.customUserId }}
          command: ["/bin/sh"]
          args:
            - -c
            - |
              usermod -u {{ .Values.customUserId }} rospo
              cd /home/rospo
              sudo -u rospo rospo /etc/rospo/rospo.yaml
          {{- else }}
          args: ["/etc/rospo/rospo.yaml"]
          {{- end}}
          ports:
            - name: ssh
              containerPort: 2222
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- if .Values.chroot.enabled }}
            - mountPath: /data
              name: {{ include "rospo.fullname" . }}-chroot
            {{- end }}
            {{- range .Values.extraVolumeMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              subPath: {{ .subPath }}
            {{- end }}
            - name: {{ include "rospo.fullname" . }}
              mountPath: /etc/rospo/rospo.yaml
              subPath: rospo.yaml
            - name: {{ include "rospo.fullname" . }}-secret
              mountPath: /etc/rospo/server_key
              subPath: server_key
            - name: {{ include "rospo.fullname" . }}-secret-auth
              mountPath: /etc/rospo/authorized_keys
              subPath: authorized_keys
      volumes:
        {{- range .Values.extraVolumeMounts }}
        - name: {{ .name }}
          persistentVolumeClaim:
            claimName: {{ .name }}
        {{- end }}
        - name: {{ include "rospo.fullname" . }}
          configMap:
            name: {{ include "rospo.fullname" . }}
        - name: {{ include "rospo.fullname" . }}-secret
          secret:
            secretName: {{ include "rospo.fullname" . }}
        - name: {{ include "rospo.fullname" . }}-secret-auth
          secret:
            secretName: {{ include "rospo.fullname" . }}-auth
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

  {{- if .Values.chroot.enabled }}
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: {{ include "rospo.fullname" . }}-chroot
      labels:
        {{- include "rospo.labels" . | nindent 8 }}
    spec:
      accessModes:
        - ReadWriteOnce
      {{- if .Values.chroot.storageClassName }}
      storageClassName: {{ .Values.chroot.storageClassName }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.chroot.size }}
  {{- end }}
