{{- if .Values.chroot.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "rospo.fullname" . }}-chroot
  labels:
    {{- include "rospo.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.chroot.storageClassName }}
  storageClassName: {{ .Values.chroot.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.chroot.size }}

{{- end }}