# Default values for k8svpn.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ferama/k8svpn
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""


internalSubnet: "10.13.16.0"
allowedips: "172.21.0.0/16"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
service:
  type: LoadBalancer
  port: 51820

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
